---
apiVersion: v1
kind: Service
metadata:                     
  name: loghme-backend-service
  labels:
    app: loghme-app
spec:                         
  type: NodePort
  selector:
    app: loghme-app
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30735
    
    
---
    
  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loghme-backend-deployment
  labels:
    app: loghme-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxUnavailable: 1
       maxSurge: 0
  selector:
    matchLabels:
      app: loghme-app
  template:
    metadata:
      labels:
        app: loghme-app
    spec:  
      containers:
      - name: loghme-back-end  
        image: aryanhaddadi/aryan_docker_hub:Loghme_Back_End
        imagePullPolicy: Always
        ports:
          - name: http  
            containerPort: 8080
        resources:
          requests:
            cpu: 0.2
            memory: "200Mi"
          limits:
            cpu: 0.4
            memory: "400Mi"  
      imagePullSecrets:
        - name: regcred            
