---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: loghme-app-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi


---    


apiVersion: v1
kind: Service
metadata:
  name: loghme-database-service
  labels:
    app: loghme-app-db
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    app: loghme-app-db


---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: loghme-database-deployment
  labels: 
    app: loghme-app-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loghme-app-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: loghme-app-db
    spec:
      containers:
      - image: mysql
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-pass
              key: password
        - name: MYSQL_USER
          valueFrom:
              secretKeyRef:
                name: mysql-user-pass
                key: username
        - name: MYSQL_PASSWORD
          valueFrom:
              secretKeyRef:
                name: mysql-user-pass
                key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-db-name
              key: database
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        resources:
          limits:
            cpu: 0.4
            memory: "400Mi"
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
          